---
abstract: 'Yet another XS implemented Redis Client'
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  Test::More: '0.98'
  Test::RedisServer: '0.14'
  Test::TCP: '2'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Devel::CheckCompiler: '0.04'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v1.1.0, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Redis-Jet
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Redis::Jet:
    file: lib/Redis/Jet.pm
    version: '0.02'
requires:
  perl: '5.008005'
resources:
  bugtracker: https://github.com/kazeburo/Redis-Jet/issues
  homepage: https://github.com/kazeburo/Redis-Jet
  repository: git://github.com/kazeburo/Redis-Jet.git
version: '0.02'
x_authority: cpan:KAZEBURO
